### PR TITLE
eslint version note

### PR DESCRIPTION
**Pull request by loay**

### CODE REVIEW

**Comment by loay** [comment]
@superkhau  PTAL

**Comment by superkhau** [comment]
@loay I edited the PR directly, please squash the commit and merge! LGTM. :ship:

**Comment by superkhau** [comment]
Actually please change the commit message to something more descriptive.

"Add versioning details to ESLint guide"

**Comment by superkhau** [comment]
Squash, edit commit msg and :ship: LGTM. ;)

**Pull request merged**
