### PR TITLE
Add formatting comment to FA owners doc

### PR DESCRIPTION
**Pull request by superkhau**
@strongloop/loopback-dev PTAL

### CODE REVIEW

**Comment by bajtos** [comment]
Since the formatting comment is useful only to people editing the file, not to the people viewing the rendered markdown output, I am proposing to use XML/HTML style comment instead of quote style.

**Comment by bajtos** [comment]
> Since the formatting comment is useful only to people editing the file, not to the people viewing the rendered markdown output, I am proposing to use XML/HTML style comment instead of quote style.

I have pushed extra commit applying this change.

**Comment by bajtos** [comment]
>  clahub — One or more of this commit's parents has contributors who have 

^^^ it makes me wonder how did we end up with that warning?

**Comment by bajtos** [comment]
Other than the comments above, the patch LGTM. @superkhau please wait for more thumb-ups and squash the commits before merging.

**Comment by richardpringle** [comment]
Woah, why is @gunjpan linked but no one else?

**Comment by superkhau** [comment]
>^^^ it makes me wonder how did we end up with that warning?

Good question. @rmg ^

**Comment by superkhau** [comment]
>Woah, why is @gunjpan linked but no one else? 

@richardpringle I only added one example as to how we should format the links for each person on the team because after I merged this in, I wanted everyone else to help with filling in the links for their own names. FYI, we probably need to link the repos soon too, but I will send another PR with how that one should be formatted (it's going to be standard markdown, but there are a few weird cases where repos are mapped to specific files like `memory` connector` instead of a repo -- wanted to think about this for awhile first).

**Comment by rmg** [comment]
Someone used the web-ui to make edits and those commits are flagged as being committed by https://github.com/web-flow - and that "user" has not signed the CLA.

I think the quick fix is for someone to clone and rebase this branch locally so that the commits get reattributed to a real committer.

**Comment by superkhau** [comment]
FYI, the rebase suggested by @rmg fixed it. He is also making a change to CLAHub to prevent this from happening again.

**Comment by superkhau** [comment]
>more thumb-ups and squash the commits before merging.

How many?

**Comment by richardpringle** [comment]
@superkhau, I would say remove the link before you merge. Each commit on master should be a complete version of the document, there should be no inconsistencies.

Same with linking the repos, it should all be done in one shot, or done incrementally on a separate branch and then merged as one commit.

**Comment by superkhau** [comment]
>@superkhau, I would say remove the link before you merge. Each commit on master should be a >complete version of the document, there should be no inconsistencies.
>
>Same with linking the repos, it should all be done in one shot, or done incrementally on a >separate branch and then merged as one commit.

@richardpringle What does that have to do with this commit of adding one comment? I'm confused.

**Comment by superkhau** [comment]
@richardpringle Ah, I think you were referring to the other PR now that I think about it.

>I would say remove the link before you merge. Each commit on master should be a complete version of the document, there should be no inconsistencies.

That has already been merged, but feel free to submit a PR to revert it if it's bothering you that much.

>Same with linking the repos, it should all be done in one shot, or done incrementally on a separate branch and then merged as one commit.

This may not happen as one commit as the goal is to split the work amongst the team. Each person will have their own single commits, etc.

**Comment by richardpringle** [comment]
@superkhau

For linking the repos, why wouldn't you do that on a separate branch? In the history on master, you have "incomplete" documents, which is no good in my mind. You would never do the same thing with code.

**Comment by superkhau** [comment]
>For linking the repos, why wouldn't you do that on a separate branch? In the history on master, you have "incomplete" documents, which is no good in my mind. You would never do the same thing with code.

We are bikeshedding here, I removed the link as you suggested.

**Pull request merged**
