### PR TITLE
Make users linkable

### PR DESCRIPTION
**Pull request by Amir-61**
* Make users linkable

From @bajtos:
>Can we eventually get user handles clickable too?

Related https://github.com/strongloop/loopback-contributor-docs/pull/13#issuecomment-250387220

Connect to https://github.com/strongloop/loopback-contributor-docs/issues/14

/to: @strongloop/loopback-dev @bajtos @superkhau

### CODE REVIEW

**Comment by 0candy** [comment]
So next step is to get the labels clickable?

**Comment by Amir-61** [comment]
@0candy 

>So next step is to get the labels clickable?

What label? You mean FA labels? Linkable to what? GH issues?

**Comment by superkhau** [comment]
@0candy @Amir-61 Yes, most likely a good idea

**Comment by Amir-61** [comment]
@0candy @superkhau 

>@0candy @Amir-61 Yes, most likely a good idea

How would you do that? Right now each FA consists of multiple repos so you cannot link each FA label to multiple GH issues on different repos; on the other hand, we already linked repos; I think thats enough. With that being said, lets please leave that discussion out of scope of these changes, we can discuss it later.

**Comment by superkhau** [comment]
That way we can see all issues that are assigned to you across all repos in that particular FA.

**Comment by davidcheung** [comment]
I think either way is fine, i think the username link might be slightly useful for the community? 
and the link u posted would be more useful for maintainers (fa owners). 

Speaking from a point of view that I didn't find not having a link particularly an inconvenient to begin with.

**Comment by superkhau** [comment]
Actually I'm reconsidering this since you already did the legwork @Amir-61 -- Let's just land your changes and if we think of something more useful, update it then. :+1: and thanks for the help. ;)

**Comment by bajtos** [comment]
+1, thank you Amir for this update.

> How would you do that? Right now each FA consists of multiple repos so you cannot link each FA label to multiple GH issues on different repos;

You can search across multiple repositories. Here is an example that lists all `juggler-relation` issues in all `strongloop` repositories (excluding `scrum-loopback` in `strongloop-internal`):

https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Astrongloop+label%3Ajuggler-relations

See GitHub help for more details:
 - https://help.github.com/articles/searching-issues/
 - https://help.github.com/articles/search-syntax/

**Comment by Amir-61** [comment]
>You can search across multiple repositories. Here is an example that lists all juggler-relation issues in all strongloop repositories (excluding scrum-loopback in strongloop-internal):

>https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Astrongloop+label%3Ajuggler-relations

Nice! I was not aware that you could query it in multiple repos. I'll update it then... Thanks!

**Comment by superkhau** [comment]
>You can search across multiple repositories...

This is exactly the answer I was looking for. Didn't notice user:strongloop was possible. We can probably add two filters then: user:strongloop OR user:strongloop-internal if possible (I'm not sure if GH supports OR syntax yet -- I know it supports AND).

**Pull request merged**
